/* empty css                      */(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const i of n)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function o(n){const i={};return n.integrity&&(i.integrity=n.integrity),n.referrerPolicy&&(i.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?i.credentials="include":n.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(n){if(n.ep)return;n.ep=!0;const i=o(n);fetch(n.href,i)}})();document.addEventListener("DOMContentLoaded",()=>{console.log("DOM Loaded. Initializing Machina Shift..."),v(),g(),p(),h(),E(),y(),w(),x()});function v(){typeof lucide<"u"&&lucide.createIcons()}function g(){if(typeof Lenis>"u")return;const t=new Lenis({duration:1.2,easing:o=>Math.min(1,1.001-Math.pow(2,-10*o)),smooth:!0});function e(o){t.raf(o),requestAnimationFrame(e)}requestAnimationFrame(e)}function p(){const t=document.querySelector(".header__burger"),e=document.querySelector(".mobile-menu__close"),o=document.querySelector(".mobile-menu"),r=document.querySelectorAll(".mobile-menu__link, .mobile-menu__btn");if(!t||!o)return;const n=()=>{o.classList.toggle("is-open"),document.body.style.overflow=o.classList.contains("is-open")?"hidden":""};t.addEventListener("click",i=>{i.stopPropagation(),n()}),e&&e.addEventListener("click",n),r.forEach(i=>i.addEventListener("click",n))}function h(){const t=document.getElementById("canvas-container");if(!(!t||typeof THREE>"u"))try{let d=function(){requestAnimationFrame(d),a.uTime.value=f.getElapsedTime(),u.x+=(c.x-u.x)*.08,u.y+=(c.y-u.y)*.08,r.render(e,o)};const e=new THREE.Scene,o=new THREE.OrthographicCamera(-1,1,1,-1,0,1),r=new THREE.WebGLRenderer({alpha:!0,antialias:!0});r.setSize(window.innerWidth,window.innerHeight),r.setPixelRatio(Math.min(window.devicePixelRatio,2)),t.appendChild(r.domElement);const n=new THREE.TextureLoader;n.setCrossOrigin("anonymous");const s=n.load("https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop",()=>{},void 0,()=>console.log("Texture err")),u=new THREE.Vector2(0,0),c=new THREE.Vector2(0,0),a={uTime:{value:0},uTexture:{value:s},uMouse:{value:u},uResolution:{value:new THREE.Vector2(window.innerWidth,window.innerHeight)}},l=new THREE.ShaderMaterial({uniforms:a,vertexShader:"varying vec2 vUv; void main() { vUv = uv; gl_Position = vec4(position, 1.0); }",fragmentShader:`
              uniform float uTime;
              uniform sampler2D uTexture;
              uniform vec2 uMouse;
              uniform vec2 uResolution;
              varying vec2 vUv;
              void main() {
                  vec2 uv = vUv;
                  float aspect = uResolution.x / uResolution.y;
                  vec2 m = uMouse; m.x *= aspect;
                  vec2 uva = uv; uva.x *= aspect;
                  float dist = distance(uva, m);
                  float influence = smoothstep(0.45, 0.0, dist);
                  uv.x += influence * (uv.x - uMouse.x) * 0.2;
                  uv.y += influence * (uv.y - uMouse.y) * 0.2;
                  vec4 color = texture2D(uTexture, uv);
                  color.rgb *= 0.35;
                  color.rgb += vec3(influence * 0.2, influence * 0.4, 0.0);
                  gl_FragColor = color;
              }
          `});e.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),l)),document.addEventListener("mousemove",m=>{c.x=m.clientX/window.innerWidth,c.y=1-m.clientY/window.innerHeight}),window.addEventListener("resize",()=>{r.setSize(window.innerWidth,window.innerHeight),a.uResolution.value.x=window.innerWidth,a.uResolution.value.y=window.innerHeight});const f=new THREE.Clock;d()}catch(e){console.error(e)}}function E(){const t=document.querySelector(".stats-grid"),e=document.querySelectorAll(".stat-number");let o=!1;if(!t||!e.length)return;new IntersectionObserver(n=>{n[0].isIntersecting&&!o&&(o=!0,e.forEach(i=>{const s=parseFloat(i.getAttribute("data-target")),u=s%1!==0;let c=0;const a=s/50,l=setInterval(()=>{c+=a,c>=s&&(c=s,clearInterval(l)),i.innerText=u?c.toFixed(1):Math.round(c)},30)}))},{threshold:.5}).observe(t)}function y(){document.querySelectorAll(".accordion-header").forEach(t=>{t.addEventListener("click",()=>{const e=t.classList.contains("active");document.querySelectorAll(".accordion-header").forEach(o=>{o.classList.remove("active"),o.nextElementSibling.style.maxHeight=null}),e||(t.classList.add("active"),t.nextElementSibling.style.maxHeight=t.nextElementSibling.scrollHeight+"px")})})}function w(){const t=document.getElementById("lead-form"),e=document.getElementById("form-message");t&&t.addEventListener("submit",o=>{if(o.preventDefault(),document.getElementById("captcha").value!="8"){e.textContent="Ошибка: 5 + 3 = 8",e.className="form-message error";return}const r=t.querySelector("button"),n=r.textContent;r.textContent="...",r.disabled=!0,setTimeout(()=>{e.textContent="Отправлено!",e.className="form-message success",t.reset(),r.textContent=n,r.disabled=!1},1500)})}function x(){const t=document.getElementById("cookie-popup"),e=document.getElementById("accept-cookies"),o="machina_cookie_v3";!t||!e||(localStorage.getItem(o)||setTimeout(()=>{t.classList.add("show"),console.log("Popup Triggered")},1500),e.addEventListener("click",()=>{localStorage.setItem(o,"true"),t.classList.remove("show")}))}
//# sourceMappingURL=index.js.map
